# Generated by Django 5.2.6 on 2025-09-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('upc', models.CharField(blank=True, max_length=20, null=True)),
                ('copies', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
