# Generated by Django 5.2.6 on 2025-09-10 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0002_movies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
        migrations.RenameModel(
            old_name='OtherProducts',
            new_name='OtherProduct',
        ),
    ]
