# Generated by Django 5.2.6 on 2025-09-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_isbnentry_book_categories_book_description_book_isbn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isbnentry',
            name='isbn',
            field=models.CharField(max_length=20),
        ),
    ]
