# Generated by Django 5.2.6 on 2025-09-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_isbnentry_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='copies',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=20),
        ),
    ]
