# Generated by Django 5.2.6 on 2025-09-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isbnentry',
            name='isbn',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
