# Generated by Django 5.2.6 on 2025-09-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_isbnentry_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isbnentry',
            name='isbn',
            field=models.CharField(max_length=20),
        ),
    ]
