# Generated by Django 5.2.6 on 2025-09-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_isbnentry_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='hardback_copies',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='new_copies',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='papperback_copies',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='used_copies',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
