# Generated by Django 5.2.6 on 2025-09-23 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_hardback_copies_book_new_copies_and_more'),
        ('books', '0008_book_price'),
    ]

    operations = [
    ]
