# Generated by Django 5.2.6 on 2025-09-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_merge_20250923_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='hardback_copies',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='new_copies',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='papperback_copies',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='used_copies',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
