# Generated by Django 5.2.6 on 2025-09-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_book_hardback_copies_alter_book_new_copies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
