# Generated by Django 5.2.6 on 2025-09-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_customerrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='book_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
