# Generated by Django 5.2.6 on 2025-09-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_customerrequest_book_title_customerrequest_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='date',
            field=models.DateField(blank=True, default=None),
        ),
    ]
