# Generated by Django 5.2.6 on 2025-10-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='hardback_copies',
        ),
        migrations.RemoveField(
            model_name='book',
            name='new_copies',
        ),
        migrations.RemoveField(
            model_name='book',
            name='papperback_copies',
        ),
        migrations.RemoveField(
            model_name='book',
            name='used_copies',
        ),
        migrations.AddField(
            model_name='book',
            name='binding',
            field=models.CharField(choices=[('hardback', 'Hardback'), ('paperback', 'Paperback')], default='paperback', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used')], default='used', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='is_xlib',
            field=models.BooleanField(default=False, verbose_name='Ex-Library'),
        ),
    ]
