# Generated by Django 5.2.6 on 2025-10-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_remove_book_hardback_copies_remove_book_new_copies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='binding',
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_xlib',
        ),
        migrations.AddField(
            model_name='isbnentry',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('good', 'Good'), ('acceptable', 'Acceptable')], default='good', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('good', 'Good'), ('acceptable', 'Acceptable')], default='good', max_length=20),
        ),
    ]
