# Generated by Django 5.2.6 on 2025-10-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_remove_book_binding_remove_book_is_xlib_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='copie_type',
            field=models.CharField(choices=[('hardcover', 'Hardcover'), ('paperback', 'Paperback'), ('audiobook', 'Audiobook')], default='hardcover', max_length=20),
        ),
        migrations.AddField(
            model_name='isbnentry',
            name='copie_type',
            field=models.CharField(choices=[('hardcover', 'Hardcover'), ('paperback', 'Paperback'), ('audiobook', 'Audiobook')], default='hardcover', max_length=20),
        ),
    ]
