# Generated by Django 5.2.6 on 2025-10-14 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_book_copie_type_isbnentry_copie_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='copie_type',
        ),
        migrations.RemoveField(
            model_name='isbnentry',
            name='copie_type',
        ),
    ]
